apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: ci-user
    namespace: kube-system
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: ci-role
subjects:
    - kind: ServiceAccount
      name: ci-user
      namespace: kube-system

