apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: ci-role
rules:
    - apiGroups: [""] # "" indicates the core API group
      resources:
          - configmaps
          - pods
          - secrets
          - services
          - namespaces
          - persistentvolumes
          - persistentvolumeclaims
      verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
    - apiGroups:
          - batch
      resources:
          - jobs
      verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
    - apiGroups:
          - apps
      resources:
          - deployments
          - replicasets  # needed for 'helm upgrade --wait'
      verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
    - apiGroups:
          - autoscaling
      resources:
          - horizontalpodautoscalers
      verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
    - apiGroups:
          - networking.k8s.io
      resources:
          - ingresses
      verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
    - apiGroups:
          - monitoring.coreos.com
      resources:
          - prometheusrules
          - servicemonitors
      verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
    - apiGroups:
          - networking.k8s.io
      resources:
          - networkpolicies
      verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
    - apiGroups:
          - traefik.containo.us
      resources:
          - ingressroutes
          - middlewares
      verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch

